package enpit.sample.adf12.restadfbc.model.service.common.serviceinterface;

import enpit.sample.adf12.restadfbc.model.query.common.DepartmentsViewSDO;
import enpit.sample.adf12.restadfbc.model.query.common.EmployeesViewSDO;

import java.util.List;

import javax.ejb.Local;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.common.service.types.ProcessControl;
import oracle.jbo.common.service.types.ProcessData;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 18 19:56:53 CEST 2013
// ---------------------------------------------------------------------
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/",
                    name = "HRAppModuleService",
                    wsdlLocation =
                    "enpit/sample/adf12/restadfbc/model/service/common/serviceinterface/HRAppModuleService.wsdl")
@SDODatabinding(schemaLocation =
                "enpit/sample/adf12/restadfbc/model/service/common/serviceinterface/HRAppModuleService.xsd")

public interface HRAppModuleService {


    public static final String NAME = "{/enpit/sample/adf12/restadfbc/model/service/common/}HRAppModuleService";

    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/createDepartmentsView1",
               operationName = "createDepartmentsView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "createDepartmentsView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "createDepartmentsView1Response")
    @WebResult(name = "result")
    DepartmentsViewSDO createDepartmentsView1(@WebParam(mode = WebParam.Mode.IN, name = "departmentsView1")
                                              DepartmentsViewSDO departmentsView1) throws ServiceException;

    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/updateDepartmentsView1",
               operationName = "updateDepartmentsView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "updateDepartmentsView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "updateDepartmentsView1Response")
    @WebResult(name = "result")
    DepartmentsViewSDO updateDepartmentsView1(@WebParam(mode = WebParam.Mode.IN, name = "departmentsView1")
                                              DepartmentsViewSDO departmentsView1) throws ServiceException;


    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/mergeDepartmentsView1",
               operationName = "mergeDepartmentsView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "mergeDepartmentsView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "mergeDepartmentsView1Response")
    @WebResult(name = "result")
    DepartmentsViewSDO mergeDepartmentsView1(@WebParam(mode = WebParam.Mode.IN, name = "departmentsView1")
                                             DepartmentsViewSDO departmentsView1) throws ServiceException;


    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/getEmployeesView1",
               operationName = "getEmployeesView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "getEmployeesView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "getEmployeesView1Response")
    @WebResult(name = "result")
    EmployeesViewSDO getEmployeesView1(@WebParam(mode = WebParam.Mode.IN, name = "employeeId")
                                       Integer employeeId) throws ServiceException;

    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/updateEmployeesView1",
               operationName = "updateEmployeesView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "updateEmployeesView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "updateEmployeesView1Response")
    @WebResult(name = "result")
    EmployeesViewSDO updateEmployeesView1(@WebParam(mode = WebParam.Mode.IN, name = "employeesView1")
                                          EmployeesViewSDO employeesView1) throws ServiceException;

    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/getDepartmentsView1",
               operationName = "getDepartmentsView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "getDepartmentsView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "getDepartmentsView1Response")
    @WebResult(name = "result")
    DepartmentsViewSDO getDepartmentsView1(@WebParam(mode = WebParam.Mode.IN, name = "departmentId")
                                           Integer departmentId) throws ServiceException;

    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/findDepartmentsView1",
               operationName = "findDepartmentsView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "findDepartmentsView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "findDepartmentsView1Response")
    @WebResult(name = "result")
    List<DepartmentsViewSDO> findDepartmentsView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                                  FindCriteria findCriteria,
                                                  @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                                  FindControl findControl) throws ServiceException;

    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/createEmployeesView1",
               operationName = "createEmployeesView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "createEmployeesView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "createEmployeesView1Response")
    @WebResult(name = "result")
    EmployeesViewSDO createEmployeesView1(@WebParam(mode = WebParam.Mode.IN, name = "employeesView1")
                                          EmployeesViewSDO employeesView1) throws ServiceException;


    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/mergeEmployeesView1",
               operationName = "mergeEmployeesView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "mergeEmployeesView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "mergeEmployeesView1Response")
    @WebResult(name = "result")
    EmployeesViewSDO mergeEmployeesView1(@WebParam(mode = WebParam.Mode.IN, name = "employeesView1")
                                         EmployeesViewSDO employeesView1) throws ServiceException;

    @WebMethod(action = "/enpit/sample/adf12/restadfbc/model/service/common/findEmployeesView1",
               operationName = "findEmployeesView1")
    @RequestWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                    localName = "findEmployeesView1")
    @ResponseWrapper(targetNamespace = "/enpit/sample/adf12/restadfbc/model/service/common/types/",
                     localName = "findEmployeesView1Response")
    @WebResult(name = "result")
    List<EmployeesViewSDO> findEmployeesView1(@WebParam(mode = WebParam.Mode.IN, name = "findCriteria")
                                              FindCriteria findCriteria,
                                              @WebParam(mode = WebParam.Mode.IN, name = "findControl")
                                              FindControl findControl) throws ServiceException;
}

